name: matrices
description: A Dart matrix computing library, providing basic operations of linear algebra
version: 1.1.0
homepage: https://gitee.com/abandoft/matrices
# publish_to: https://pub.dartlang.org
environment: 
  sdk: ">=2.16.0 <3.0.0"