name: matrices
description: A Dart matrix computing library, providing basic operations of linear algebra
version: 1.1.3
homepage: https://github.com/abandoft/matrices

environment: 
  sdk: ">=2.15.0 <3.0.0"