name: matrices
description: A Dart matrix computing library, providing basic operations of linear algebra
version: 1.0.9
homepage: https://gitee.com/abandoft/matrices

environment:
  sdk: ">=2.17.5 <3.0.0"