name: matrices
description: A Dart matrix computing library, providing basic operations of linear algebra
version: 1.0.11
homepage: https://gitee.com/abandoft/matrices
# publish_to: https://pub.dartlang.org
environment: 
  sdk: ">=2.17.5 <3.0.0"